---
interfaces:
  Loopback0:
    address: '192.168.100.3/32'
  Ethernet1:
    address: '10.10.10.5/31'
  Ethernet2:
    address: '10.10.10.13/31'
  Ethernet3:
    address: '10.100.102.1/24'
bgp:
  as_number: 64523
  router_id: '192.168.100.3'
  neighbors:
    10.10.10.4:
       remote_as: 65500
       ipv4: true
       evpn: true
       send-community: true
       loopback: '192.168.101.1'
    10.10.10.12:
       remote_as: 65500
       ipv4: true
       evpn: true
       send-community: true
       loopback: '192.168.101.2'
