---
role: leaf
interfaces:
  Loopback0:
    address: '192.168.100.6/32'
  Ethernet11:
    address: '10.10.20.3/31'
  Ethernet12:
    address: '10.10.20.11/31'
bgp:
  as_number: 64526
  router_id: '192.168.100.6'
  neighbors:
    10.10.20.2:
       remote_as: 65501
       ipv4: true
       evpn: true
       send-community: true
       loopback: '192.168.101.1'
    10.10.20.10:
       remote_as: 65502
       ipv4: true
       evpn: true
       send-community: true
       loopback: '192.168.101.2'
vxlan:
  vlans:
