---
interfaces:
  Loopback0:
    address: '192.168.100.2/32'
  Ethernet1:
    address: '10.10.10.3/31'
  Ethernet2:
    address: '10.10.10.11/31'
bgp:
  as_number: 64522
  router_id: '192.168.100.2'
  neighbors:
    10.10.10.2:
       remote_as: 65500
       ipv4: true
       evpn: true
       send-community: true
       loopback: '192.168.101.1'
    10.10.10.10:
       remote_as: 65500
       ipv4: true
       evpn: true
       send-community: true
       loopback: '192.168.101.2'
