---
role: leaf
interfaces:
  Loopback0:
    address: '192.168.100.5/32'
  Ethernet11:
    address: '10.10.20.1/31'
  Ethernet12:
    address: '10.10.20.9/31'
bgp:
  as_number: 64525
  router_id: '192.168.100.5'
  neighbors:
    10.10.20.0:
       remote_as: 65501
       ipv4: true
       evpn: true
       send-community: true
       loopback: '192.168.101.1'
    10.10.20.8:
       remote_as: 65502
       ipv4: true
       evpn: true
       send-community: true
       loopback: '192.168.101.2'
vxlan:
  vlans:
    100:
      vni: 10100
      interfaces:
        - 'Ethernet1'
      rd: '192.168.100.5:10100'
      export_rt: '100:100'
      import_rt: '100:100'
  vrfs:
    vrf10000:
      vni: 10000
      vlan: 100
      rd: '192.168.100.5:10000'
      export_rt: '10.0.0.0:10000'
      import_rt: '10.0.0.0:10000'
